name: dio_cookie_caching_handler
description: An Dio interceptor stores cookies and puts back to every requests made.
version: 0.0.8
homepage: https://github.com/hurelhuyag/dio_cookie_cached_handler

environment:
  sdk: '>=2.19.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
